HelloProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='home'),
    path('post/<int:post_id>/', views.post, name='post'),
    path('exemplo/', views.exemplo, name='exemplo'),
] 

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import Http404
from blog.data import posts

def blog(request):
    print('Blog 4!')
    
    return render(
        request, 
        'blog/index.html',
        {
            # 'text': 'Estamos no Blog',
            'title': ' Blog',
            'posts':posts
        }
    )

def post(request, post_id):
    found_post = None
    
    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break
        
    if found_post is None:
        raise Http404('Post não encontrado!')
        
    context = {
        # 'title': found_post['title'] + ' - ',
        'title': 'Post ' + str(post_id),
        'post': found_post
    }
    
    return render(
        request, 
        'blog/post.html',
        context
    )

def exemplo(request):
    print('Exemplo 4!')
    
    return render(
        request, 
        'blog/exemplo.html',
        {
            'text': 'Estamos no Exemplo',
            'title': ' Exemplo'
        }
    )

home/views.py
from django.shortcuts import render

# from django.http import HttpResponse

# Create your views here.

def home(request):
    print('Home!')
    
    context = {
        'text': 'Estamos na Home',
        'title': ' Home'
    }
    
    return render(
        request, 
        'home/index.html',
        context,
    )

blog/templates/blog/exemplo.html
{% extends "global/base.html" %}

{% comment %} {% block title %}Exemplo do App{% endblock title %} {% endcomment %}

{% block texto %}{{ text }}{% endblock texto %}

blog/templates/blog/index.html
{% extends "global/base.html" %}


{% block texto %}{{ text }}{% endblock texto %}

{% block posts %}
    {% for post in posts %}
    
        {% include 'global/partials/postblock.html' %}
        
    {% endfor %}

{% endblock posts %}

blog/templates/blog/post.html
{% extends "global/base.html" %}


{% block texto %}{{ text }}{% endblock texto %}

{% block posts %}
<article class="post single-post">
    <header>
        <h1 class="post_title">
            <a href="{% url "blog:post" post.id %}">
                {{post.title}}
            </a>
        </h1>
    </header>
    <div class="post_body">{{post.body}}</div>
</article>

{% endblock posts %}

home/templates/home/index.html
{% extends "global/base.html" %}

{% comment %} {% block title %}Home do App{% endblock title %} {% endcomment %}

{% block texto %}{{ text }}{% endblock texto %}